### ISSUE TITLE
Cycling TODO

### ISSUE THREAD

**Issue by corbt** [corbt/HNReact#1]
I'll document to-do/done tasks here until a better release management process becomes necessary.
- [ ] Swipe-to-refresh
- [ ] Ability to follow users
- [ ] Show unread comments
- [ ] Release on Play Store
